OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
need correct password root

OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)") (Background on this error at: http://sqlalche.me/e/e3q8)
incorrect PORT number being used.  fix port number

OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'sadorski'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
attempting to coonnect as user other than root

 File "server.py", line 4, in <module>
    mysql = MySQLConnector(app,'friendsdb')
  File "/Users/sadorski/Desktop/Projects/SQL stuff/Friends/mysqlconnection.py", line 40, in MySQLConnector
    return MySQLConnection(app, db)
  File "/Users/sadorski/Desktop/Projects/SQL stuff/Friends/mysqlconnection.py", line 9, in __init__
    'database': db33, # we got db as an argument
NameError: global name 'db33' is not defined
name of database had to be db